### ISSUE TITLE
fav.pl shipped?

### ISSUE THREAD

**Issue by toddr** [metacpan/metacpan-client#109]
Did you mean to ship fav.pl?

**Comment by oalders** [comment]
Oops! It could be added to the `examples` dir, I think.

**Comment by mickeyn** [comment]
No, this looks like old junk (using facets for aggregations, I think this comes from an old version of `examples/top20_favorites.pl`).
I'll remove it

**Comment by mickeyn** [comment]
removed. will be gone in next release.
