### ISSUE TITLE
How to fetch the issues of a release/distribution?

### ISSUE THREAD

**Issue by szabgab** [metacpan/metacpan-client#115]
I did not see any mention of the `issues` in the documentation of MetaCPAN::Client. 

Ideally I think they would come as part of the information of the `recent` call or the `release` call, but till that happens it would be nice to have alternative ways documented.

**Comment by haarg** [comment]
That is accessible via the `distribution` call.

**Comment by oalders** [comment]
@szabgab since issues don't belong to any particular release, we keep the counts in the `distribution` endpoint as @haarg pointed out.

**Comment by szabgab** [comment]
Thanks both of you. So if I'd like to display the issue count on https://cpan-digger.perlmaven.com/ for every distribution, what would be the best way to fetch that? Looking at the source code of MetaCPAN I already found a file on RT from where I could download https://github.com/szabgab/CPAN-Digger/issues/36 and I guess I could also find how you fetch the date from GitHub, but I wonder, is there an easier way?

**Comment by oalders** [comment]
The endpoint would be https://fastapi.metacpan.org/v1/distribution/CPAN-Digger See also https://metacpan.org/pod/MetaCPAN::Client::Distribution

**Comment by oalders** [comment]
I think our numbers do get out of sync, so we could also look into that if you see a lot of disparity between our reported numbers and the actual issue trackers.
