### ISSUE TITLE
List of the files in a given distribution?

### ISSUE THREAD

**Issue by szabgab** [metacpan/metacpan-client#30]
Is there an easy way to fetch that list?
Can I fetch the list of modules in a distro?
Can I fetch the list of files with POD in a distro?

**Comment by szabgab** [comment]
Though as I realized later the question probably should be ```s/distribution/release/```

**Comment by mickeyn** [comment]
sorry for the very late response, not sure why I didn't see this one before:

you can do something like that for `files in release` and the subset `files with pod`:

```perl
my $mcpan = MetaCPAN::Client->new( version => 'v1' );
my $files = $mcpan->file({ release => 'MetaCPAN-Client-1.000000' });
while ( my $f = $files->next ) {
    my $pod = $f->pod;

    ...
}
```

For modules, you can do something like:
```perl
my $release = $mcpan->release({ name => 'MetaCPAN-Client-1.000000' });
my $modules = $release->next->provides;
```

HTH

(closing as this is an old issue, feel free to reopen if you need to)
