### ISSUE TITLE
Question: Convert dependency data obtained by MetaCPAN::Client to cpanfile?

### ISSUE THREAD

**Issue by zhouzhen1** [metacpan/metacpan-client#41]
I'm just asking this as I would like to get module dependency data in cpanfile (or CPAN::Meta::Prereqs) format from data fetched via MetaCPAN::Client. I guess it's not unusual case, so someone else might have made some shortcut there. If there's no existing stuffs it's fine for me to do it myself. Thanks!

**Comment by mickeyn** [comment]
`perl -MMetaCPAN::Client -MDDP -e'&p( MetaCPAN::Client->new->release("Moose")->dependency )'`
?

**Comment by zhouzhen1** [comment]
Thanks. I think this can be closed now.
