### ISSUE TITLE
CPANTESTERS results please

### ISSUE THREAD

**Issue by Tux** [metacpan/metacpan-client#45]
This M::C unrelated snippet currently returns invalid values and often timeouts
``` perl
	# CPANTESTER results
	$opt_v > 1 and warn " Fetch cpantesters\n";
	!defined $data->{cptst} and
	    $data->{cptst} =
	      ($r = CPAN::Testers::WWW::Reports::Query::AJAX->new (dist => $dist))
		? [ $r->pass, $r->na, $r->fail, $r->unknown ]
		: [ "", "", "", "" ];
```
I would like to see valid actual (recent) values for CPANTESTERS results for a given distribution, somewhat like
```
$ perl -MMetaCPAN::Client -MData::Peek -wE'DDumper (MetaCPAN::Client->new (version => "v1")->distribution ("Text-CSV_XS")->cpantesters)'
{   pass  => 214,
    fail  => 0,
    na    => 0,
    }
```

**Comment by mickeyn** [comment]
seems like we already have it (at least supported)... it is in the `release` index as `tests` (also the attribute name):

```
$ perl -Ilib -MMetaCPAN::Client -MDDP -e' my $mcpan = MetaCPAN::Client->new( version => "v1" )->release( { distribution => "Moose" } ); while ( my $r = $mcpan->next ) { &p([ $r->name, $r->tests ] ) }'
```

Not all releases have the test results, so for now they will be undef if missing.

@oalders do you know if there's any reason why we're missing tests info for releases? is it something in the works?

**Comment by Tux** [comment]
And they are neither valid nor recent/up-to-date:
```
$ perl -MMetaCPAN::Client -MDP -wE'my$m=MetaCPAN::Client->new (version => "v1")->release({distribution=>"Text-CSV_XS"});while (my $r = $m->next){ DDumper [ $r->name, $r->tests ] if $r->name =~ /1\.2[345]/ }'
[   'Text-CSV_XS-1.23',
    {   fail             => 0,
        na               => 0,
        pass             => 573,
        unknown          => 0
        }
    ]
[   'Text-CSV_XS-1.24',
    undef
    ]
[   'Text-CSV_XS-1.25',
    undef
    ]
```
Which kinda defeats the purpose
At the moment of writing, 1.25 is 388/0/0, 1.24 is 752/0/0, and 1.23 is 1132/0/0

**Comment by haarg** [comment]
That certainly isn't an issue with the client.  Most likely that is metacpan/metacpan-web#1630, which is an issue on the CPAN Testers side.

**Comment by mickeyn** [comment]
closing as there is an issue open for it https://github.com/metacpan/metacpan-web/issues/1769
(not a metacpan-web issue either, but will be looked at)

client will serve the data automatically if it's there.
