### ISSUE TITLE
Searches with fields param broken with Search::Elasticsearch 5.01

### ISSUE THREAD

**Issue by pghmcfc** [metacpan/metacpan-client#48]
I'm doing lookups like this:
```
my $mcpan = MetaCPAN::Client->new();
# Look up latest stable release
my $results = $mcpan->release(
        {       all => [ { distribution => $distro    },
                         { maturity     => 'released' }, ]
        },
        { fields => "authorized,date,name,version" }
);
````
and that works fine at the moment, but after trying Search::Elasticsearch 5.01 I got:
```
[Param] ** Unknown param (fields) in (search) request. See docs at: http://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html, called from sub Search::Elasticsearch::Client::5_0::Direct::scroll_helper at /usr/share/perl5/vendor_perl/MetaCPAN/Client/Request.pm line 147.
```
I've reverted to S::E 2.03 for now. I'm not even sure if this was supposed to work really; I don't know which version of Elasticsearch is being used with MetaCPAN.

**Comment by oalders** [comment]
Can you upgrade to the latest `MetaCPAN::Client` and upgrade to the `v1` api?

```
my $mcpan = MetaCPAN::Client->new(
    version => 'v1'
);
```

Let us know if that fixes it for you?

**Comment by mickeyn** [comment]
the new Search::Elasticsearch is oriented towards ES 5.
according to https://v1.metacpan.org/changes/release/DRTECH/Search-Elasticsearch-5.00
it's not clear to me yet if it supports multiple clients and the 2_0 (for v1) or 0_90 (for v0) don't come by default.

I'll release a new MetaCPAN::Client with a version limit to ensure we don't use that version for now.

**Comment by mickeyn** [comment]
release 1.026000 will limit the module version to ensure this is not breaking the client.

**Comment by mickeyn** [comment]
also opened https://github.com/elastic/elasticsearch-perl/issues/109

**Comment by pghmcfc** [comment]
> Can you upgrade to the latest MetaCPAN::Client and upgrade to the v1 api?
>
> my $mcpan = MetaCPAN::Client->new(
>     version => 'v1'
> );
>
> Let us know if that fixes it for you?

That doesn't help (same error message).

I've also tried installing Search-Elasticsearch-Client-2_0 and requesting the use of that client (the previous default) specifically:
```
--- /usr/share/perl5/vendor_perl/MetaCPAN/Client/Request.pm.orig	2016-08-30 13:18:24.000000000 +0100
+++ /usr/share/perl5/vendor_perl/MetaCPAN/Client/Request.pm	2016-10-20 10:14:25.856013885 +0100
@@ -129,6 +129,7 @@
     my $params = shift;
 
     my $es = Search::Elasticsearch->new(
+        client           => '2_0::Direct',
         nodes            => [ 'https://' . $self->domain ],
         cxn_pool         => 'Static::NoPing',
         send_get_body_as => 'POST',
```
Then it fails with: "isa check for "scroller" failed: scroller must be an Search::Elasticsearch::Scroll object at /usr/share/perl5/vendor_perl/MetaCPAN/Client.pm line 259."

The Search::Elasticsearch::Scroll class no longer exists and there are API version specific classes now, such as Search::Elasticsearch::Client::5_0::Scroll and Search::Elasticsearch::Client::2_0::Scroll. So that's another thing that'll need to be taken account of.

**Comment by mickeyn** [comment]
@pghmcfc thanks for testing.
I already confirmed the new releases of Search::Elasticsearch don't work well with the client and I limited the requirement of its version in the latest client release from yesterday.
