### ISSUE TITLE
add "changes" endpoint

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#57]
I'd like to be able to call this endpoint from the metacpan-client:

https://fastapi.metacpan.org/v1/changes/KARJALA/XML-MyXML-0.9001

**Comment by mickeyn** [comment]
sure, I think that can be added.
will play around with it.

**Comment by mickeyn** [comment]
supported in 2.009000 (through Release objects - see `examples/changes.pl`)
