### ISSUE TITLE
ability to sort the results of ->all by any field I want

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#58]
I'd like to call ```->all('releases', {...})``` and have ES sort the search results by any field I want.

**Comment by mickeyn** [comment]
that is not possible to do as the ES scroller (through Search::Elasticsearch) does not support sorting (this has to do with how ES works).

**Comment by akarelas** [comment]
I'm pretty sure I've done a large search with scroller (paging by 4 or 5.000 rows at a time), in which I got to choose the sort order. All this at the metacpan v0 API, using a normal UserAgent's POST method (```Mojo::UserAgent``` in particular, though it doesn't matter which). Why can't the same be done with MetaCPAN::Client? Here's the query I talk about:

```perl
my $tx = $ua->post('http://api.metacpan.org/v0/release/_search?scroll=2m', json => {
    query => { match_all => {} },
    fields => [qw/ name distribution date version version_numified maturity author /],
    sort => { date => 'desc' },
    size => 4_000,
    filter => {
        and => [
            { range => { date => { gte => "$start_year-01-01T00:00:00Z" } } },
            { range => { date => { lte => $end_dt } } },
            { term => { authorized => \1 } },
            { term => { maturity => 'released' } },
        ],
    },
});
```

**Comment by mickeyn** [comment]
The scroller in the client is using 'scan' scroll_type to pull large amount of data efficiently, this does not support sorting over a sharded cluster (v0 is a single node server, v1 is a cluster).
