### ISSUE TITLE
documentation order & indenting is wrong

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#59]
On page https://metacpan.org/pod/MetaCPAN::Client you get the phrase (under method ```all```):
"When called with a second parameter containing a hash ref, will support the following keys:"
But then the keys don't appear, until AFTER download_url.
download_url should be somewhere else, out of the way, so that the keys appear right underneath all.

**Comment by mickeyn** [comment]
fixed in 67913622976
