### ISSUE TITLE
version_numified should be string, not number

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#60]
When I do `p $release` I get version_numified as a number, not a string.

But version_numified can have many many decimal digits (more than Perl can handle in numbers, I believe), so to be precise and not lose precision, we should be able to process it and store it in a database as a string, not a number.

```
        data   {
            author             "LOCALSHOP",
            date               "2016-11-29T16:57:37",
            distribution       "WebService-Xero",
            maturity           "released",
            name               "WebService-Xero-0.10",
            version            0.10,
            version_numified   0.1
        },
        date   "2016-11-29T16:57:37"
```

**Comment by akarelas** [comment]
Hm... maybe this is a non-issue. I just saw that `$s = "4.5"; p $s` will print 4.5 (without quotes)

**Comment by haarg** [comment]
The entire point of the field is to store it as a number and allow numeric operations.  We aren't losing any precision by not representing it as a string.

**Comment by akarelas** [comment]
perl cannot correctly compare 1.000000000000000000001 with 1.000000000000000000002 numerically. That's why I say we lose precision if we get numbers back for this field.

On the other hand if perl is handed those values as strings and inserts them in a mysql database field of type DECIMAL(42,21), then mysql can compare those numbers, sort them, or whatever, with no precision lost.

Does anyone lose anything if these values are strings?

**Comment by haarg** [comment]
You lose the ability to perform numeric comparisons on it in elasticsearch, which is the entire reason for the field's existence.

PAUSE already limits version numbers to 16 characters long.

**Comment by mickeyn** [comment]
this is not a client issue, as explained by @haarg this ES mapping of the field as 'float'.
