### ISSUE TITLE
autocomplete is not as good as the real thing

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#62]
When I do: `my $ac = $mcpan->autocomplete('mojoli access');` I get 10 results, 8 of which are from the Mojolicious distribution, and none of them is "Mojolicious::Plugin::AccessLog".

On the other hand, when I do: `GET https://fastapi.metacpan.org/v1/search/autocomplete?q=mojoli+access`, I get very varied and interesting results, the first many of which contain both Mojolicious and Access in their names.

**Comment by mickeyn** [comment]
this method is using the API endpoint so there's no local logic to it.
your query is not a module name prefix so the underlying ES query can give some surprising results this is an 'autocomplete' query, not a google search.
we are currently working on replacing the autocomplete method in the API, so it will change with it.

**Comment by akarelas** [comment]
The problem was that the search term wasn't URI-encoded, when placed as a GET parameter. I posted another issue, about this, since this one closed.
