### ISSUE TITLE
autocompletion query term is not URI-encoded

### ISSUE THREAD

**Issue by akarelas** [metacpan/metacpan-client#63]
https://metacpan.org/source/MICKEY/MetaCPAN-Client-2.002000/lib/MetaCPAN/Client.pm#L182

That's why a space in the middle makes the server ignore all terms except the first one. I think it's a bug.

**Comment by mickeyn** [comment]
fixed in 4f53f864

**Comment by mickeyn** [comment]
and released (2.003000)
