### ISSUE TITLE
All objects should provide a metacpan_url method

### ISSUE THREAD

**Issue by autarch** [metacpan/metacpan-client#69]
It'd be incredibly useful if we could get URLs to a release, distribution, module, etc. on the metacpan.org website with a simple method. As it is, you have to know the exact URL scheme the website uses and construct it from object attributes.

**Comment by mickeyn** [comment]
I like the idea, though some objects are not a result of a simple URL access but an ES query served through the API (so POST req + JSON bodies).
That goes for any client request that take a structure over a simple string as input.

I rather not expose ES queries as my (long-term) goal is to decouple the client (and metacpan-web) from the backend (making it ES-unaware).
When *that* is done, I wouldn't mind exposing all API queries as we send them.

For now - would the GET requests URLs be enough for you?

**Comment by autarch** [comment]
Yeah, I didn't really mean _all_ objects like resultsets, just things that correspond closely to something visible from the web UI, so things like `Release`, `Author`, etc.

A `GET` URL would not be much help for what I was doing.

**Comment by oalders** [comment]
@autarch are you looking for API URLs or front end URLs?

**Comment by autarch** [comment]
I want the client API to give me _front end_ URLs.

**Comment by mickeyn** [comment]
@autarch see #74 - it will introduce the method for Module, Release & Author.
I just wanted to make sure I didn't miss anything before releasing.

(and sorry for the delay :))

**Comment by mickeyn** [comment]
from 2.008000 the metacpan_url method is supported for the following types:
Module, Release, Distribution, File & Author
