### ISSUE TITLE
How to specify time for scroller?

### ISSUE THREAD

**Issue by pghmcfc** [metacpan/metacpan-client#70]
I create a MetaCPAN::Client object and then run lots of queries through it (current release info for all modules I use locally). Of late, I've been getting errors when doing this:
```
failed to delete scroller at /usr/share/perl5/vendor_perl/MetaCPAN/Client/Scroll.pm line 160.                                         
failed to create a scrolled search at /usr/share/perl5/vendor_perl/MetaCPAN/Client/Request.pm line 129.                               
```
I suspect that this is because the scroller has lived longer than the default 5 minutes in MetaCPAN::Client::Scroll. I see that MetaCPAN::Client::Scroll has a 'time' attribute but I don't see any way to set that via MetaCPAN::Client->new / MetaCPAN::Client::Request. Am I missing something?

**Comment by mickeyn** [comment]
I can add support for passing down the time limit, but I'm afraid of that causing performance issues.
5m should be enough for the amount of data we have (1m would even make a better default) - I've ran scrolled searches of the entire big types and they never come near 5m.

Is it possible to see code that causes this issue for debugging?

Creating a longer-life scrollers on the server for the sake of slower consumption is not being very polite to the server (scrolled searches are taking up resources) - I'd say, try to consume all the data once you have the scroller object, let it go out of scope (so the DELETE req is sent) and then process your data at any pace you wish and both client and server are happy.

**Comment by pghmcfc** [comment]
Sure, the script I'm running is here:
http://subversion.city-fan.org/repos/cfo-repo/buildsys-scripts/pmv

**Comment by mickeyn** [comment]
wow, that's a lot of scrollers you're creating there :)

you can mitigate this quickly by grouping the distributions into less queries and do the data differentiation later in your Perl code - use the 'es_filter' and the 'terms' query (matches any of multi-values) instead of creating a separate scroller for each one (you may still need to do several as there's some ES limit for how many values you can pass in a single query).
e.g.
```
my $releases = $mcpan->all(
    'releases',
    {
        es_filter => {
            and => [
                { term  => { maturity => 'released' } },
                { terms => {
                    distribution => [qw<                                                                                                                      
                        ...                                                                                                                                   
                        Algorithm-C3                                                                                                                          
                        Algorithm-Diff                                                                                                                        
                        Algorithm-Diff-XS                                                                                                                     
                        Any-Moose                                                                                                                             
                        AnyEvent                                                                                                                              
                        ...                                                                                                                                   
                    >] } }
            ]
        }
    }
);
```

There are probably more ways of optimizing it on your end - please let me know how it goes once you tried it.

**Comment by pghmcfc** [comment]
This approach looks promising but I'd like to be able to specify fields as well as the filter and I don't seem to be able to do it - the filter seems to be all that is passed on. What I probably really need is the ability to specify a source filter so I only get back the fields in _source that I'm actually interested in, which would save a lot of network traffic. Is there any way to combine that with es_filter?

**Comment by mickeyn** [comment]
you can specify fields (or _source entries) through the 'fields' keyword in the same hash ref:
```
my $releases = $mcpan->all(
    'releases',
    {
        es_filter => {
            ...
        },
        fields => [qw< ... >],
    }
);
```

**Comment by pghmcfc** [comment]
I tried that but it seemed to ignore the fields parameter when I specified it. I still got back all of the fields as part of _source.

**Comment by mickeyn** [comment]
I'm not sure I follow you, here's an example:
```perl
use MetaCPAN::Client;
use DDP;
p MetaCPAN::Client->new->all(
    'releases',
    {
        es_filter => {
            and => [
                { term  => { maturity => 'released' } },
                { terms => {
                    distribution => [qw<                                      
                        Algorithm-C3                                          
                        Any-Moose                                             
                        AnyEvent                                              
                    >] } }
            ]
        },
        fields => ['abstract'],
    }
)->next;
```
output:
```perl
MetaCPAN::Client::Release  {
    Parents       Moo::Object
    public methods (23) : abstract, archive, author, authorized, date, dependency, distribution, DOES, download_url, first, id, license, maturity, metadata, name, new, provides, resources, stat, status, tests, version, version_numified
    private methods (1) : _known_fields
    internals: {
        data   {
            abstract   "provide framework for multiple event loops"
        }
    }
}
```

what am I missing?

**Comment by pghmcfc** [comment]
Doing almost exactly the same thing:
```
use MetaCPAN::Client;
use DDP output => 'stdout';
my $mcpan = MetaCPAN::Client->new();
my $releases = $mcpan->all(
        'releases',
        {
                es_filter => {
                        and => [
                                { term    => { maturity     => 'released'   } },
                                { terms   => { distribution => [qw< Algorithm-C3 Any-Moose AnyEvent >] } }
                        ]
                },
                fields => ['abstract'],
        }
);
p $releases->next;
```
I get:
```
MetaCPAN::Client::Release  {
    Parents       Moo::Object
    public methods (23) : abstract, archive, author, authorized, date, dependency, distribution, DOES, download_url, first, id, licens
e, maturity, metadata, name, new, provides, resources, stat, status, tests, version, version_numified
    private methods (1) : _known_fields
    internals: {
        data   {
            abstract           "provide framework for multiple event loops",
            archive            "AnyEvent-0.4.tar.gz",
            author             "MLEHMANN",
            authorized         1,
            date               "2005-12-30T01:29:43",
            dependency         [
                [0] {
                    module         "Event",
                    phase          "runtime",
                    relationship   "requires",
                    version        0.86
                }
            ],
            distribution       "AnyEvent",
            download_url       "https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/AnyEvent-0.4.tar.gz",
            first              0,
            id                 "oSq7IsV6q5iIPepldwlzULKeook",
            license            [
                [0] "unknown"
            ],
            maturity           "released",
            metadata           {
                abstract         "unknown",
                author           [
                    [0] "unknown"
                ],
                dynamic_config   1,
                generated_by     "ExtUtils::MakeMaker version 6.23, CPAN::Meta::Converter version 2.150005",
                license          [
                    [0] "unknown"
                ],
                meta-spec        {
                    url       "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
                    version   2
                },
                name             "AnyEvent",
                no_index         {
                    directory   [
                        [0] "t",
                        [1] "xt",
                        [2] "inc",
                        [3] "local",
                        [4] "perl5",
                        [5] "fatlib",
                        [6] "example",
                        [7] "blib",
                        [8] "examples",
                        [9] "eg"
                    ]
                },
                prereqs          {
                    runtime   {
                        requires   {
                            Event   0.86
                        }
                    }
                },
                release_status   "stable",
                version          0.4,
                x_installdirs    "site",
                x_version_from   "lib/AnyEvent.pm"
            },
            name               "AnyEvent-0.4",
            provides           [
                [0] "AnyEvent",
                [1] "AnyEvent::Impl::Coro",
                [2] "AnyEvent::Impl::Event",
                [3] "AnyEvent::Impl::Glib",
                [4] "AnyEvent::Impl::Tk"
            ],
            resources          {},
            stat               {
                gid     1009,
                mode    33188,
                mtime   1135906183,
                size    6920,
                uid     1009
            },
            status             "backpan",
            tests              {
                fail      0,
                na        0,
                pass      2,
                unknown   0
            },
            version            0.4,
            version_numified   0.4
        }
    }
}
```

**Comment by mickeyn** [comment]
odd, running your code I still get the same response as I did.

which version of the client are you running?

**Comment by pghmcfc** [comment]
2.005000. That was the first thing I though of too...

**Comment by mickeyn** [comment]
hmm... I think I wasn't running the latest... let me dig into it.

**Comment by mickeyn** [comment]
I found we don't pass the fields in this specific case (not even sure why as it was documented)
I have a fix ready and will do a release with it soon.

**Comment by mickeyn** [comment]
I released 2.006000 (will be available soon) with the missing support for 'fields' and additional support for '_source' - which you will probably need in case you're fetching non-indexed fields (requires some understanding of the ES side of it, but I don't think there's a reasonable way around the ES limitation here)

Note that pulling _source entries means the server fetches the entire document instead of using indexed fields... so performance-wise you're better off using 'fields' if they satisfy what you need.

Please install the new version and let me know how it goes.

**Comment by pghmcfc** [comment]
Now I get the same output as you do :-)

**Comment by mickeyn** [comment]
cool, so moving forward - are these changes and the advice above helping with your original problem?

**Comment by pghmcfc** [comment]
Yes, now I've updated the script to fetch data for multiple dists in the same query and it seems quite a lot faster and less prone to errors. Thanks for the suggestion!

**Comment by mickeyn** [comment]
awesome.

can we close this issue then? I rather not allow long scrollers at the moment, as you see they are not really required.

**Comment by pghmcfc** [comment]
Indeed.

**Comment by reyjrar** [comment]
Too little. too late, but the size attribute may also come into play.. Scroll timeouts only occur if the scroll isn't rerun within the timeout, ie, each request resets the scroll timeout.  The current limit is 100, but making that user configurable to fewer results, maybe helpful?

**Comment by mickeyn** [comment]
@reyjrar thanks for the tip - it's not too late :)

The default in our scoller is 100, but the Client sends a 1000 as a size parameter, so that's the actual number.

We can add size parameter, but since the user doesn't get a bulk of results (that's only used internally for buffer management) but an iterator - it might cause some confusion on the user end.

I'll prepare a change to allow size/time settings for pro-users and document it as such with the appropriate warnings.
