### ISSUE TITLE
failed to delete scroller at .../MetaCPAN/Client/Scroll.pm line 162.

### ISSUE THREAD

**Issue by neilb** [metacpan/metacpan-client#81]
I have a script which is, in outline:

    created MetaCPAN::Client
    iterate on releases, collecting information
    do a bunch of processing on the information
    exit

I came back to see that the script had finished, with the final line of output being:

    failed to delete scroller at .../MetaCPAN/Client/Scroll.pm line 162.

I assume resources on the server side time out, which is what's causing this, but given it's cleanup in a DESTROY (another assumption), maybe this could be suppressed?

**Comment by mickeyn** [comment]
pushed the fix, will be in next release.

**Comment by neilb** [comment]
:+1:

**Comment by mickeyn** [comment]
released 2.011000

**Comment by neilb** [comment]
Thanks @mickeyn
