### ISSUE TITLE
t/api/author.t fails

### ISSUE THREAD

**Issue by eserte** [metacpan/metacpan-client#83]
`t/api/author.t` started to fail recently:
```
Use of uninitialized value $_ in pattern match (m//) at t/api/author.t line 78.

#   Failed test 'This Dave has a Gmail account'
#   at t/api/author.t line 78.
```
(error repeats a couple of times).

**Comment by mickeyn** [comment]
@eserte thanks for reporting.
Found, fixed & released a fix in 2.012000.
Please reopen if problem reappears.
