### ISSUE TITLE
specifying fields in requests can break array type checking

### ISSUE THREAD

**Issue by mark-5** [metacpan/metacpan-client#84]
Elasticsearch isn't always smart about returning an array type field as an array, when field params are specified.

For instance, if you try to search for an array type field such as "provides", and a result only has a single value, Elasticsearch can return this field as a scalar. This breaks the type checking in MetaCPAN::Client::Role::Entity.
```
$ perl -MMetaCPAN::Client -E 'say MetaCPAN::Client->new->release({name => "App-cpanminus-1.7043"}, {fields => ["provides"]})->next->provides;'

```

Maybe the type checking should gracefully promote scalars to arrays? Not sure what the best solution would be here.

**Comment by mickeyn** [comment]
fixed in the last release.
