### ISSUE TITLE
`fields` is documented that it will accept a csv string, but fails if it's not an arrayref

### ISSUE THREAD

**Issue by grr** [metacpan/metacpan-client#87]
The docs for [all()](https://metacpan.org/pod/MetaCPAN::Client#all), says see [SEARCH PARAMS](https://metacpan.org/pod/MetaCPAN::Client#SEARCH-PARAMS),  and there it says fields can be passed as a csv string. But if you try using that, it will fail with "fields must be an arrayref".
Example code triggering it:

    use MetaCPAN::Client;
    my $r = MetaCPAN::Client->new->all('releases', { fields => 'author,date' });

**Comment by mickeyn** [comment]
fixed in release 2.016000

The technical reason was that 'all' requests are handled by a different code path, so the 'field' parameter you passed went down to ES which rejected it.

Please upgrade and this should work for you.
