### ISSUE TITLE
"Wrong type of query arguments" after upgrading from v0-era MetaCPAN::Client

### ISSUE THREAD

**Issue by sartak** [metacpan/metacpan-client#88]
Hi Mickey et al,

One of my cronjobs started throwing errors about v0 being shut off. (Congratulations by the way!) It used MetaCPAN::Client, and so I upgraded from a 1.x series version to 2.016000 to get the bump to the v1 api. However, the following code, which worked before...

```
my $mcpan = MetaCPAN::Client->new(
  ua => HTTP::Tiny::Mech->new(
    mechua => WWW::Mechanize::Cached->new(
      cache => CHI->new(
        driver     => 'File',
        root_dir   => 'var/cache/',
        expires_in => '1h',
      ),
    ),
  ),
);

my $releases = $mcpan->ssearch(
    file => {__MATCH_ALL__ => 1}, {
        body => {
            query  => { match_all => {} },
            fields => [ "release" ],
            filter => {
                and => [
                    { term => { path   => "inc/Module/Install/RTx.pm"} },
                    { term => { status => "latest"  } },
                ],
            },
        },
    },
);

while (my $release = $releases->next) {
    my $release = $mcpan->release({name => $release->{fields}{release}})->next;
    next unless $release;
    …
```

...now after upgrading throws this warning and error:

```
WARN - Use of uninitialized value $val in pattern match (m//) at /path/to/MetaCPAN/Client/Request.pm line 249.
Wrong type of query arguments at (eval 1019) line 17
```

Is this something you've seen before? Anything jump out at you? The error message isn't particularly enlightening 😅

**Comment by oalders** [comment]
Hi @sartak. Does this persist if you clear the cache?

**Comment by sartak** [comment]
Yes, I'm afraid so

**Comment by mickeyn** [comment]
hi @sartak 

The main problem in your code is this:
```
while (my $release = $releases->next) {
    my $release = $mcpan->release({name => $release->{fields}{release}})->next;
```
I don't see why you need to send a query for a release when you already have that release (object, btw).

You should also not use ssearch directly, it's an internal method (I know, bad name. but it's part of an internal module as well... not the Client).

The working redo of your code would be something like:
```
use DDP;
...
my $releases = $mcpan->all('files', {
    es_filter => {
        and => [
            { term => { path   => "inc/Module/Install/RTx.pm"} },
            { term => { status => "latest"  } },
        ],
    },
    fields => [ "release" ],
});

while (my $release = $releases->next) {
    p $release;
}
```

HTH

**Comment by mickeyn** [comment]
@sartak can we please close this one?

**Comment by sartak** [comment]
Yes

iPhoneから送信

H29/08/10 23:53、Mickey <notifications@github.com> のメッセージ:
