### ISSUE TITLE
reverse_dependencies() points to an invalid URL

### ISSUE THREAD

**Issue by stevieb9** [metacpan/metacpan-client#89]
I'm wondering if the REST API for the reverse dependency URL has changed.

    perl -MMetaCPAN::Client -E 'say $MetaCPAN::Client::VERSION'
    2.016000

Test code:

    use warnings;
    use strict;

    use MetaCPAN::Client;

    my $module = 'MetaCPAN::Client';

    my $mcpan = MetaCPAN::Client->new;

    my $rs = $mcpan->reverse_dependencies($module);

    my @revdeps;

    while (my $release = $rs->next){
        push @revdeps, $release->distribution;
    }

    print "$_\n" for @revdeps;

Output/Error:

    Failed to fetch 'https://fastapi.metacpan.org//search/reverse_dependencies/MetaCPAN-Client': Not Found at /home/pi/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.1/MetaCPAN/Client.pm line 315.

Upon going to [cpan.org](http://www.cpan.org) and hovering over the revdeps link for this distribution, I see:

    https://metacpan.org/requires/distribution/MetaCPAN-Client?sort=[[2,1]]

Much different than the one in the error message. The link in the error fails to work in the browser as well (as expected), throwing a `404`.

Just wondering if I'm missing something here or not.

**Comment by mickeyn** [comment]
reverse_dependencies upstream link was recently changed.
I updated the link - thanks for the report.

I released a new version with the fix (2.017000)

**Comment by stevieb9** [comment]
Thanks @mickeyn!
